### ISSUE TITLE
Create a Responsive NavBar with TW and DaisyUI

### ISSUE THREAD

**Issue by wesdevpro** [ntohq/education-trail#41]

**Comment by wesdevpro** [comment]
```
Failed to compile.

Error: Cannot find module 'daisyui/src/colors/themes'
Require stack:
- E:\GitHub\education-trail\src\EducationTrail\ClientApp\tailwind.config.js
ERROR in ./src/assets/css/Layout.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/react-scripts/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/assets/css/Layout.css)
Module build failed (from ./node_modules/react-scripts/node_modules/postcss-loader/dist/cjs.js):
Error: Cannot find module 'daisyui/src/colors/themes'
Require stack:
- E:\GitHub\education-trail\src\EducationTrail\ClientApp\tailwind.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at _resolve (E:\GitHub\education-trail\src\EducationTrail\ClientApp\node_modules\jiti\dist\jiti.js:1:250100)
    at jiti (E:\GitHub\education-trail\src\EducationTrail\ClientApp\node_modules\jiti\dist\jiti.js:1:252409)
    at E:\GitHub\education-trail\src\EducationTrail\ClientApp\tailwind.config.js:9:14
    at evalModule (E:\GitHub\education-trail\src\EducationTrail\ClientApp\node_modules\jiti\dist\jiti.js:1:255106)
    at jiti (E:\GitHub\education-trail\src\EducationTrail\ClientApp\node_modules\jiti\dist\jiti.js:1:253034)
    at E:\GitHub\education-trail\src\EducationTrail\ClientApp\node_modules\tailwindcss\lib\lib\load-config.js:37:30
    at loadConfig (E:\GitHub\education-trail\src\EducationTrail\ClientApp\node_modules\tailwindcss\lib\lib\load-config.js:39:6)
    at getTailwindConfig (E:\GitHub\education-trail\src\EducationTrail\ClientApp\node_modules\tailwindcss\lib\lib\setupTrackingContext.js:71:116)

ERROR in ./src/assets/css/core.css (./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!./node_modules/react-scripts/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!./node_modules/source-map-loader/dist/cjs.js!./src/assets/css/core.css)
Module build failed (from ./node_modules/react-scripts/node_modules/postcss-loader/dist/cjs.js):
Error: Cannot find module 'daisyui/src/colors/themes'
Require stack:
- E:\GitHub\education-trail\src\EducationTrail\ClientApp\tailwind.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Function.resolve (node:internal/modules/cjs/helpers:116:19)
    at _resolve (E:\GitHub\education-trail\src\EducationTrail\ClientApp\node_modules\jiti\dist\jiti.js:1:250100)
    at jiti (E:\GitHub\education-trail\src\EducationTrail\ClientApp\node_modules\jiti\dist\jiti.js:1:252409)
    at E:\GitHub\education-trail\src\EducationTrail\ClientApp\tailwind.config.js:9:14
    at evalModule (E:\GitHub\education-trail\src\EducationTrail\ClientApp\node_modules\jiti\dist\jiti.js:1:255106)
    at jiti (E:\GitHub\education-trail\src\EducationTrail\ClientApp\node_modules\jiti\dist\jiti.js:1:253034)
    at E:\GitHub\education-trail\src\EducationTrail\ClientApp\node_modules\tailwindcss\lib\lib\load-config.js:37:30
    at loadConfig (E:\GitHub\education-trail\src\EducationTrail\ClientApp\node_modules\tailwindcss\lib\lib\load-config.js:39:6)
    at getTailwindConfig (E:\GitHub\education-trail\src\EducationTrail\ClientApp\node_modules\tailwindcss\lib\lib\setupTrackingContext.js:71:116)

webpack compiled with 2 errors
```

**Comment by wesdevpro** [comment]
Part 2: Design for mobile. 👇

**Comment by wesdevpro** [comment]
### Next Steps
- [ ] Add JavaScript to Handle mobile navigation
